# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1060, 700)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/traffic/Icon/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow>QWidget{background-color: rgb(41, 39, 40);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabright = QtWidgets.QTabWidget(self.centralwidget)
        self.tabright.setGeometry(QtCore.QRect(210, 19, 851, 721))
        self.tabright.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabright.setStyleSheet("QTabBar::tab{width: 0; height: 0 ;margin: 0; padding: 0;}\n"
"QTabWidget::pane { border: 0; }\n"
"QTabWidget>QWidget>QWidget{background: #F5F6FA}")
        self.tabright.setObjectName("tabright")
        self.tabhome = QtWidgets.QWidget()
        self.tabhome.setObjectName("tabhome")
        self.frmhome1 = QtWidgets.QFrame(self.tabhome)
        self.frmhome1.setGeometry(QtCore.QRect(80, 420, 321, 191))
        self.frmhome1.setStyleSheet("QFrame#frmhome1 {\n"
"background: white;\n"
"border-radius: 10px;\n"
"border: 1px solid #D3D3D3;}")
        self.frmhome1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmhome1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmhome1.setObjectName("frmhome1")
        self.btnbrowse1 = QtWidgets.QPushButton(self.frmhome1)
        self.btnbrowse1.setGeometry(QtCore.QRect(200, 120, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnbrowse1.setFont(font)
        self.btnbrowse1.setStyleSheet("QPushButton#btnbrowse1n:hover {background-color: black;\n"
"color: white;}\n"
"QPushButton#btnbrowse1 {\n"
"border-radius: 5px;\n"
"background: rgb(41, 39, 40);\n"
"color: white;\n"
"}")
        self.btnbrowse1.setObjectName("btnbrowse1")
        self.btnpicthome = QtWidgets.QPushButton(self.frmhome1)
        self.btnpicthome.setGeometry(QtCore.QRect(20, 10, 101, 101))
        self.btnpicthome.setStyleSheet("QPushButton#btnpicthome {\n"
"border: none;\n"
"border-radius: 100px;\n"
"}")
        self.btnpicthome.setLocale(QtCore.QLocale(QtCore.QLocale.Indonesian, QtCore.QLocale.Indonesia))
        self.btnpicthome.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/traffic/Icon/landscape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnpicthome.setIcon(icon1)
        self.btnpicthome.setIconSize(QtCore.QSize(150, 100))
        self.btnpicthome.setObjectName("btnpicthome")
        self.label_4 = QtWidgets.QLabel(self.frmhome1)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.frmhome2 = QtWidgets.QFrame(self.tabhome)
        self.frmhome2.setGeometry(QtCore.QRect(450, 520, 331, 91))
        self.frmhome2.setStyleSheet("QFrame#frmhome2 {\n"
"background: white;\n"
"border-radius: 10px;\n"
"border: 1px solid #D3D3D3;}")
        self.frmhome2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmhome2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmhome2.setObjectName("frmhome2")
        self.btnreporthome = QtWidgets.QPushButton(self.frmhome2)
        self.btnreporthome.setGeometry(QtCore.QRect(210, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnreporthome.setFont(font)
        self.btnreporthome.setStyleSheet("QPushButton#btnreporthome:hover {background-color: black;\n"
"color: white;}\n"
"QPushButton#btnreporthome {\n"
"border-radius: 5px;\n"
"background: rgb(41, 39, 40);\n"
"color: white;\n"
"}")
        self.btnreporthome.setObjectName("btnreporthome")
        self.label_6 = QtWidgets.QLabel(self.frmhome2)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.frmhome3 = QtWidgets.QFrame(self.tabhome)
        self.frmhome3.setGeometry(QtCore.QRect(570, 310, 211, 81))
        self.frmhome3.setStyleSheet("QFrame#frmhome3 {\n"
"background: white;\n"
"border-radius: 10px;\n"
"border: 1px solid #D3D3D3;}")
        self.frmhome3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmhome3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmhome3.setObjectName("frmhome3")
        self.lcdtime = QtWidgets.QLCDNumber(self.frmhome3)
        self.lcdtime.setGeometry(QtCore.QRect(10, 10, 191, 61))
        self.lcdtime.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdtime.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdtime.setNumDigits(8)
        self.lcdtime.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdtime.setObjectName("lcdtime")
        self.frmhome4 = QtWidgets.QFrame(self.tabhome)
        self.frmhome4.setGeometry(QtCore.QRect(80, 300, 321, 91))
        self.frmhome4.setStyleSheet("QFrame#frmhome4 {\n"
"background: white;\n"
"border-radius: 10px;\n"
"border: 1px solid #D3D3D3;}")
        self.frmhome4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmhome4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmhome4.setObjectName("frmhome4")
        self.label_7 = QtWidgets.QLabel(self.frmhome4)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lbldatehome = QtWidgets.QLabel(self.frmhome4)
        self.lbldatehome.setGeometry(QtCore.QRect(20, 40, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbldatehome.setFont(font)
        self.lbldatehome.setObjectName("lbldatehome")
        self.frmhome5 = QtWidgets.QFrame(self.tabhome)
        self.frmhome5.setGeometry(QtCore.QRect(80, 80, 701, 181))
        self.frmhome5.setStyleSheet("QFrame#frmhome5 {\n"
"background: white;\n"
"border-radius: 10px;\n"
"border: 1px solid #D3D3D3;}")
        self.frmhome5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmhome5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmhome5.setObjectName("frmhome5")
        self.btnlogo0 = QtWidgets.QPushButton(self.frmhome5)
        self.btnlogo0.setGeometry(QtCore.QRect(30, 20, 141, 141))
        self.btnlogo0.setStyleSheet("QPushButton#btnlogo0 {\n"
"border: none;\n"
"border-radius: 70px;\n"
"background:  #FFCF06;\n"
"}")
        self.btnlogo0.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/traffic/Icon/crossing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnlogo0.setIcon(icon2)
        self.btnlogo0.setIconSize(QtCore.QSize(70, 70))
        self.btnlogo0.setObjectName("btnlogo0")
        self.label_9 = QtWidgets.QLabel(self.frmhome5)
        self.label_9.setGeometry(QtCore.QRect(200, 70, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.tabright.addTab(self.tabhome, "")
        self.tabsetup = QtWidgets.QWidget()
        self.tabsetup.setObjectName("tabsetup")
        self.frmtraffic = QtWidgets.QFrame(self.tabsetup)
        self.frmtraffic.setGeometry(QtCore.QRect(100, 170, 311, 361))
        self.frmtraffic.setStyleSheet("QFrame#frmtraffic {\n"
"background: white;\n"
"border-radius: 10px;\n"
"border: 1px solid #D3D3D3;}")
        self.frmtraffic.setFrameShape(QtWidgets.QFrame.Panel)
        self.frmtraffic.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmtraffic.setLineWidth(5)
        self.frmtraffic.setMidLineWidth(2)
        self.frmtraffic.setObjectName("frmtraffic")
        self.label = QtWidgets.QLabel(self.frmtraffic)
        self.label.setGeometry(QtCore.QRect(20, 10, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background: white;")
        self.label.setObjectName("label")
        self.btntrafficlight = QtWidgets.QPushButton(self.frmtraffic)
        self.btntrafficlight.setGeometry(QtCore.QRect(50, 80, 211, 211))
        self.btntrafficlight.setStyleSheet("QPushButton#btntrafficlight:hover {background-color: #dbdbdb;}\n"
"QPushButton#btntrafficlight {\n"
"border: none;\n"
"border-radius: 100px;\n"
"background: white;\n"
"}")
        self.btntrafficlight.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/traffic/Icon/traffic-light.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btntrafficlight.setIcon(icon3)
        self.btntrafficlight.setIconSize(QtCore.QSize(200, 200))
        self.btntrafficlight.setObjectName("btntrafficlight")
        self.frmroi = QtWidgets.QFrame(self.tabsetup)
        self.frmroi.setGeometry(QtCore.QRect(460, 170, 311, 361))
        self.frmroi.setStyleSheet("QFrame#frmroi {\n"
"background: white;\n"
"border-radius: 10px;\n"
"border: 1px solid #D3D3D3;}")
        self.frmroi.setFrameShape(QtWidgets.QFrame.Panel)
        self.frmroi.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmroi.setLineWidth(5)
        self.frmroi.setMidLineWidth(2)
        self.frmroi.setObjectName("frmroi")
        self.label_2 = QtWidgets.QLabel(self.frmroi)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background: white;")
        self.label_2.setObjectName("label_2")
        self.btnroi = QtWidgets.QPushButton(self.frmroi)
        self.btnroi.setGeometry(QtCore.QRect(50, 80, 211, 211))
        self.btnroi.setStyleSheet("QPushButton#btnroi:hover {background-color: #dbdbdb;}\n"
"QPushButton#btnroi {\n"
"border: none;\n"
"border-radius: 100px;\n"
"background: white;\n"
"}")
        self.btnroi.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/traffic/Icon/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnroi.setIcon(icon4)
        self.btnroi.setIconSize(QtCore.QSize(200, 200))
        self.btnroi.setObjectName("btnroi")
        self.tabright.addTab(self.tabsetup, "")
        self.tabmonitor = QtWidgets.QWidget()
        self.tabmonitor.setObjectName("tabmonitor")
        self.videoFrame = QtWidgets.QLabel(self.tabmonitor)
        self.videoFrame.setGeometry(QtCore.QRect(10, 110, 640, 480))
        self.videoFrame.setStyleSheet("border: 1px solid black;\n"
"background: #F5F6FA;")
        self.videoFrame.setText("")
        self.videoFrame.setPixmap(QtGui.QPixmap(":/traffic/Icon/video-camera.png"))
        self.videoFrame.setAlignment(QtCore.Qt.AlignCenter)
        self.videoFrame.setObjectName("videoFrame")
        self.listWidget = QtWidgets.QListWidget(self.tabmonitor)
        self.listWidget.setGeometry(QtCore.QRect(660, 110, 171, 480))
        self.listWidget.setLineWidth(0)
        self.listWidget.setModelColumn(0)
        self.listWidget.setObjectName("listWidget")
        self.frame = QtWidgets.QFrame(self.tabmonitor)
        self.frame.setGeometry(QtCore.QRect(320, 600, 251, 51))
        self.frame.setStyleSheet("background: white;\n"
"border-radius: 5px;\n"
"border: 1px solid #D3D3D3;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnstart = QtWidgets.QPushButton(self.frame)
        self.btnstart.setGeometry(QtCore.QRect(20, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnstart.setFont(font)
        self.btnstart.setStyleSheet("QPushButton#btnstart:hover {background-color: black;\n"
"color: white;}\n"
"QPushButton#btnstart {\n"
"border-radius: 5px;\n"
"background: rgb(41, 39, 40);\n"
"color: white;\n"
"}")
        self.btnstart.setObjectName("btnstart")
        self.btnstop = QtWidgets.QPushButton(self.frame)
        self.btnstop.setGeometry(QtCore.QRect(130, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnstop.setFont(font)
        self.btnstop.setStyleSheet("QPushButton#btnstop:hover {background-color: black;}\n"
"QPushButton#btnstop {\n"
"border-radius: 5px;\n"
"background: rgb(41, 39, 40);\n"
"color: white;\n"
"}")
        self.btnstop.setObjectName("btnstop")
        self.btnstop.raise_()
        self.btnstart.raise_()
        self.frame_2 = QtWidgets.QFrame(self.tabmonitor)
        self.frame_2.setGeometry(QtCore.QRect(10, 20, 281, 81))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame_2)
        self.lcdNumber.setGeometry(QtCore.QRect(190, 20, 81, 41))
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber.setLineWidth(1)
        self.lcdNumber.setNumDigits(3)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.btnmerah = QtWidgets.QPushButton(self.frame_2)
        self.btnmerah.setGeometry(QtCore.QRect(23, 20, 41, 41))
        self.btnmerah.setStyleSheet("QPushButton#btnmerah {\n"
"border: none;\n"
"border-radius: 100px;\n"
"}")
        self.btnmerah.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/traffic/Icon/merah.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnmerah.setIcon(icon5)
        self.btnmerah.setIconSize(QtCore.QSize(40, 40))
        self.btnmerah.setObjectName("btnmerah")
        self.btnnolight = QtWidgets.QPushButton(self.frame_2)
        self.btnnolight.setGeometry(QtCore.QRect(10, 5, 171, 71))
        self.btnnolight.setStyleSheet("QPushButton#btnnolight {\n"
"border: none;\n"
"border-radius: 100px;\n"
"background: #F5F6FA;\n"
"}")
        self.btnnolight.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/traffic/Icon/lampu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnnolight.setIcon(icon6)
        self.btnnolight.setIconSize(QtCore.QSize(170, 170))
        self.btnnolight.setObjectName("btnnolight")
        self.btnkuning = QtWidgets.QPushButton(self.frame_2)
        self.btnkuning.setGeometry(QtCore.QRect(74, 20, 41, 41))
        self.btnkuning.setStyleSheet("QPushButton#btnkuning {\n"
"border: none;\n"
"border-radius: 100px;\n"
"}")
        self.btnkuning.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/traffic/Icon/kuning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnkuning.setIcon(icon7)
        self.btnkuning.setIconSize(QtCore.QSize(40, 40))
        self.btnkuning.setObjectName("btnkuning")
        self.btnhijau = QtWidgets.QPushButton(self.frame_2)
        self.btnhijau.setGeometry(QtCore.QRect(126, 20, 41, 41))
        self.btnhijau.setStyleSheet("QPushButton#btnhijau {\n"
"border: none;\n"
"border-radius: 100px;\n"
"}")
        self.btnhijau.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/traffic/Icon/hijau.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnhijau.setIcon(icon8)
        self.btnhijau.setIconSize(QtCore.QSize(40, 40))
        self.btnhijau.setObjectName("btnhijau")
        self.btnnolight.raise_()
        self.lcdNumber.raise_()
        self.btnmerah.raise_()
        self.btnkuning.raise_()
        self.btnhijau.raise_()
        self.lcdtime2 = QtWidgets.QLCDNumber(self.tabmonitor)
        self.lcdtime2.setGeometry(QtCore.QRect(660, 40, 171, 51))
        self.lcdtime2.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdtime2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdtime2.setNumDigits(8)
        self.lcdtime2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdtime2.setProperty("intValue", 0)
        self.lcdtime2.setObjectName("lcdtime2")
        self.tabright.addTab(self.tabmonitor, "")
        self.tabreport = QtWidgets.QWidget()
        self.tabreport.setObjectName("tabreport")
        self.frmreport = QtWidgets.QFrame(self.tabreport)
        self.frmreport.setGeometry(QtCore.QRect(30, 30, 791, 611))
        self.frmreport.setStyleSheet("QFrame#frmreport {\n"
"background: white;\n"
"border-radius: 10px;\n"
"border: 1px solid #D3D3D3;}")
        self.frmreport.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmreport.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmreport.setObjectName("frmreport")
        self.btnprint = QtWidgets.QPushButton(self.frmreport)
        self.btnprint.setGeometry(QtCore.QRect(660, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnprint.setFont(font)
        self.btnprint.setStyleSheet("QPushButton#btnprint:hover {background-color: black;\n"
"color: white;}\n"
"QPushButton#btnprint {\n"
"border-radius: 5px;\n"
"background: rgb(41, 39, 40);\n"
"color: white;\n"
"}")
        self.btnprint.setObjectName("btnprint")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.frmreport)
        self.dateEdit_2.setGeometry(QtCore.QRect(190, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setStyleSheet("QDateEdit::drop-down {\n"
"    image: url(:/new/myapp/cbarrowdn.png);\n"
"    width:50px;\n"
"    height:15px;\n"
"    subcontrol-position: right top;\n"
"    subcontrol-origin:margin;\n"
"    background-color: white;\n"
"    border-style: solid;\n"
"    border-width: 4px;\n"
"    border-color: rgb(100,100,100);\n"
"   spacing: 5px; \n"
"}\n"
"QDateEdit\n"
"{\n"
"    background-color: white;\n"
"    spacing: 5px; \n"
"}")
        self.dateEdit_2.setLocale(QtCore.QLocale(QtCore.QLocale.Indonesian, QtCore.QLocale.Indonesia))
        self.dateEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_2.setMinimumDate(QtCore.QDate(2019, 6, 1))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.btnopen = QtWidgets.QPushButton(self.frmreport)
        self.btnopen.setGeometry(QtCore.QRect(30, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnopen.setFont(font)
        self.btnopen.setStyleSheet("QPushButton#btnopen:hover {background-color: black;\n"
"color: white;}\n"
"QPushButton#btnopen {\n"
"border-radius: 5px;\n"
"background: rgb(41, 39, 40);\n"
"color: white;\n"
"}")
        self.btnopen.setObjectName("btnopen")
        self.btnsearch = QtWidgets.QPushButton(self.frmreport)
        self.btnsearch.setGeometry(QtCore.QRect(320, 80, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnsearch.setFont(font)
        self.btnsearch.setStyleSheet("QPushButton#btnsearch:hover {background-color: black;\n"
"color: white;}\n"
"QPushButton#btnsearch {\n"
"border-radius: 5px;\n"
"background: rgb(41, 39, 40);\n"
"color: white;\n"
"}")
        self.btnsearch.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/traffic/Icon/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnsearch.setIcon(icon9)
        self.btnsearch.setIconSize(QtCore.QSize(20, 20))
        self.btnsearch.setObjectName("btnsearch")
        self.tabel = QtWidgets.QTableWidget(self.frmreport)
        self.tabel.setGeometry(QtCore.QRect(30, 120, 731, 461))
        self.tabel.setStyleSheet("background: #F5F6FA\n"
"")
        self.tabel.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabel.setWordWrap(False)
        self.tabel.setColumnCount(4)
        self.tabel.setObjectName("tabel")
        self.tabel.setRowCount(0)
        self.tabel.horizontalHeader().setMinimumSectionSize(40)
        self.tabel.horizontalHeader().setStretchLastSection(True)
        self.tabel.verticalHeader().setVisible(False)
        self.dateEdit = QtWidgets.QDateEdit(self.frmreport)
        self.dateEdit.setGeometry(QtCore.QRect(30, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("QDateEdit::drop-down {\n"
"    image: url(:/new/myapp/cbarrowdn.png);\n"
"    width:50px;\n"
"    height:15px;\n"
"    subcontrol-position: right top;\n"
"    subcontrol-origin:margin;\n"
"    background-color: white;\n"
"    border-style: solid;\n"
"    border-width: 4px;\n"
"    border-color: rgb(100,100,100);\n"
"   spacing: 5px; \n"
"}\n"
"QDateEdit\n"
"{\n"
"    background-color: white;\n"
"    spacing: 5px; \n"
"}")
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setMinimumDate(QtCore.QDate(2019, 6, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.label_3 = QtWidgets.QLabel(self.frmreport)
        self.label_3.setGeometry(QtCore.QRect(160, 85, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btndelete = QtWidgets.QPushButton(self.frmreport)
        self.btndelete.setGeometry(QtCore.QRect(710, 80, 51, 31))
        self.btndelete.setStyleSheet("QPushButton#btndelete:hover {background-color: black;\n"
"color: white;}\n"
"QPushButton#btndelete {\n"
"border-radius: 5px;\n"
"background: rgb(41, 39, 40);\n"
"color: white;\n"
"}")
        self.btndelete.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/traffic/Icon/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btndelete.setIcon(icon10)
        self.btndelete.setIconSize(QtCore.QSize(20, 20))
        self.btndelete.setObjectName("btndelete")
        self.btnrefresh = QtWidgets.QPushButton(self.frmreport)
        self.btnrefresh.setGeometry(QtCore.QRect(650, 80, 51, 31))
        self.btnrefresh.setStyleSheet("QPushButton#btnrefresh:hover {background-color: black;\n"
"color: white;}\n"
"QPushButton#btnrefresh {\n"
"border-radius: 5px;\n"
"background: rgb(41, 39, 40);\n"
"color: white;\n"
"}")
        self.btnrefresh.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/traffic/Icon/refresh-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnrefresh.setIcon(icon11)
        self.btnrefresh.setIconSize(QtCore.QSize(20, 20))
        self.btnrefresh.setObjectName("btnrefresh")
        self.tabright.addTab(self.tabreport, "")
        self.tababout = QtWidgets.QWidget()
        self.tababout.setObjectName("tababout")
        self.frmabout = QtWidgets.QFrame(self.tababout)
        self.frmabout.setGeometry(QtCore.QRect(150, 150, 561, 351))
        self.frmabout.setStyleSheet("QFrame#frmabout {\n"
"background: white;\n"
"border-radius: 10px;\n"
"border: 1px solid #D3D3D3;}")
        self.frmabout.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmabout.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmabout.setObjectName("frmabout")
        self.label_5 = QtWidgets.QLabel(self.frmabout)
        self.label_5.setGeometry(QtCore.QRect(260, 60, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lblimage_2 = QtWidgets.QLabel(self.frmabout)
        self.lblimage_2.setGeometry(QtCore.QRect(260, 130, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblimage_2.setFont(font)
        self.lblimage_2.setObjectName("lblimage_2")
        self.btnlogo2 = QtWidgets.QPushButton(self.frmabout)
        self.btnlogo2.setGeometry(QtCore.QRect(30, 60, 201, 201))
        self.btnlogo2.setStyleSheet("QPushButton#btnlogo2 {\n"
"border: none;\n"
"border-radius: 100px;\n"
"background:  #FFCF06;\n"
"}")
        self.btnlogo2.setText("")
        self.btnlogo2.setIcon(icon2)
        self.btnlogo2.setIconSize(QtCore.QSize(100, 100))
        self.btnlogo2.setObjectName("btnlogo2")
        self.label_8 = QtWidgets.QLabel(self.frmabout)
        self.label_8.setGeometry(QtCore.QRect(260, 90, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lblimage_3 = QtWidgets.QLabel(self.frmabout)
        self.lblimage_3.setGeometry(QtCore.QRect(260, 280, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblimage_3.setFont(font)
        self.lblimage_3.setObjectName("lblimage_3")
        self.lblimage_4 = QtWidgets.QLabel(self.frmabout)
        self.lblimage_4.setGeometry(QtCore.QRect(260, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblimage_4.setFont(font)
        self.lblimage_4.setObjectName("lblimage_4")
        self.lblimage_5 = QtWidgets.QLabel(self.frmabout)
        self.lblimage_5.setGeometry(QtCore.QRect(380, 170, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblimage_5.setFont(font)
        self.lblimage_5.setObjectName("lblimage_5")
        self.lblimage_6 = QtWidgets.QLabel(self.frmabout)
        self.lblimage_6.setGeometry(QtCore.QRect(380, 210, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblimage_6.setFont(font)
        self.lblimage_6.setObjectName("lblimage_6")
        self.lblimage_7 = QtWidgets.QLabel(self.frmabout)
        self.lblimage_7.setGeometry(QtCore.QRect(380, 190, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblimage_7.setFont(font)
        self.lblimage_7.setObjectName("lblimage_7")
        self.lblimage_8 = QtWidgets.QLabel(self.frmabout)
        self.lblimage_8.setGeometry(QtCore.QRect(260, 250, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblimage_8.setFont(font)
        self.lblimage_8.setObjectName("lblimage_8")
        self.tabright.addTab(self.tababout, "")
        self.tablight = QtWidgets.QWidget()
        self.tablight.setObjectName("tablight")
        self.frmlight = QtWidgets.QFrame(self.tablight)
        self.frmlight.setGeometry(QtCore.QRect(250, 150, 341, 401))
        self.frmlight.setStyleSheet("\n"
"border-radius: 5px;\n"
"background: white;\n"
"border: 1px solid #D3D3D3\n"
"")
        self.frmlight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmlight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmlight.setObjectName("frmlight")
        self.btnapplylight = QtWidgets.QPushButton(self.frmlight)
        self.btnapplylight.setGeometry(QtCore.QRect(190, 350, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnapplylight.setFont(font)
        self.btnapplylight.setStyleSheet("QPushButton#btnapplylight:hover {background-color: black;\n"
"color: white;}\n"
"QPushButton#btnapplylight {\n"
"border-radius: 5px;\n"
"background: rgb(41, 39, 40);\n"
"color: white;\n"
"}")
        self.btnapplylight.setObjectName("btnapplylight")
        self.btncancellight = QtWidgets.QPushButton(self.frmlight)
        self.btncancellight.setGeometry(QtCore.QRect(60, 350, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btncancellight.setFont(font)
        self.btncancellight.setStyleSheet("QPushButton#btncancellight:hover {background-color: black;\n"
"color: white;}\n"
"QPushButton#btncancellight {\n"
"border-radius: 5px;\n"
"background: rgb(41, 39, 40);\n"
"color: white;\n"
"}")
        self.btncancellight.setObjectName("btncancellight")
        self.lbltraffic = QtWidgets.QLabel(self.frmlight)
        self.lbltraffic.setGeometry(QtCore.QRect(20, 10, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbltraffic.setFont(font)
        self.lbltraffic.setStyleSheet("border: none;")
        self.lbltraffic.setObjectName("lbltraffic")
        self.pushButton = QtWidgets.QPushButton(self.frmlight)
        self.pushButton.setGeometry(QtCore.QRect(70, 66, 61, 71))
        self.pushButton.setStyleSheet("border: none;")
        self.pushButton.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/traffic/Icon/red-bulb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon12)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frmlight)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 156, 61, 71))
        self.pushButton_2.setStyleSheet("border: none;")
        self.pushButton_2.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/traffic/Icon/yellow-bulb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon13)
        self.pushButton_2.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frmlight)
        self.pushButton_3.setGeometry(QtCore.QRect(70, 246, 61, 71))
        self.pushButton_3.setStyleSheet("border: none;")
        self.pushButton_3.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/traffic/Icon/green-bulb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon14)
        self.pushButton_3.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lbltraffic_2 = QtWidgets.QLabel(self.frmlight)
        self.lbltraffic_2.setGeometry(QtCore.QRect(70, 126, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbltraffic_2.setFont(font)
        self.lbltraffic_2.setStyleSheet("border: none;")
        self.lbltraffic_2.setObjectName("lbltraffic_2")
        self.lbltraffic_3 = QtWidgets.QLabel(self.frmlight)
        self.lbltraffic_3.setGeometry(QtCore.QRect(60, 216, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbltraffic_3.setFont(font)
        self.lbltraffic_3.setStyleSheet("border: none;")
        self.lbltraffic_3.setObjectName("lbltraffic_3")
        self.lbltraffic_4 = QtWidgets.QLabel(self.frmlight)
        self.lbltraffic_4.setGeometry(QtCore.QRect(60, 306, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbltraffic_4.setFont(font)
        self.lbltraffic_4.setStyleSheet("border: none;")
        self.lbltraffic_4.setObjectName("lbltraffic_4")
        self.lbltraffic_5 = QtWidgets.QLabel(self.frmlight)
        self.lbltraffic_5.setGeometry(QtCore.QRect(220, 90, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbltraffic_5.setFont(font)
        self.lbltraffic_5.setStyleSheet("border: none;")
        self.lbltraffic_5.setObjectName("lbltraffic_5")
        self.lbltraffic_6 = QtWidgets.QLabel(self.frmlight)
        self.lbltraffic_6.setGeometry(QtCore.QRect(220, 180, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbltraffic_6.setFont(font)
        self.lbltraffic_6.setStyleSheet("border: none;")
        self.lbltraffic_6.setObjectName("lbltraffic_6")
        self.lbltraffic_7 = QtWidgets.QLabel(self.frmlight)
        self.lbltraffic_7.setGeometry(QtCore.QRect(220, 270, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbltraffic_7.setFont(font)
        self.lbltraffic_7.setStyleSheet("border: none;")
        self.lbltraffic_7.setObjectName("lbltraffic_7")
        self.spinred = QtWidgets.QSpinBox(self.frmlight)
        self.spinred.setGeometry(QtCore.QRect(160, 90, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinred.setFont(font)
        self.spinred.setMinimum(6)
        self.spinred.setMaximum(150)
        self.spinred.setObjectName("spinred")
        self.spinyellow = QtWidgets.QSpinBox(self.frmlight)
        self.spinyellow.setGeometry(QtCore.QRect(160, 180, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinyellow.setFont(font)
        self.spinyellow.setMinimum(1)
        self.spinyellow.setMaximum(2)
        self.spinyellow.setObjectName("spinyellow")
        self.spingreen = QtWidgets.QSpinBox(self.frmlight)
        self.spingreen.setGeometry(QtCore.QRect(160, 270, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spingreen.setFont(font)
        self.spingreen.setMinimum(6)
        self.spingreen.setMaximum(100)
        self.spingreen.setObjectName("spingreen")
        self.btnback = QtWidgets.QPushButton(self.tablight)
        self.btnback.setGeometry(QtCore.QRect(180, 150, 61, 61))
        self.btnback.setStyleSheet("border: none;\n"
"background: white;\n"
"border-radius: 30px;\n"
"border: 1px solid #D3D3D3")
        self.btnback.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/traffic/Icon/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnback.setIcon(icon15)
        self.btnback.setIconSize(QtCore.QSize(35, 35))
        self.btnback.setObjectName("btnback")
        self.tabright.addTab(self.tablight, "")
        self.tabroi = QtWidgets.QWidget()
        self.tabroi.setObjectName("tabroi")
        self.frmlight_2 = QtWidgets.QFrame(self.tabroi)
        self.frmlight_2.setGeometry(QtCore.QRect(150, 190, 571, 301))
        self.frmlight_2.setStyleSheet("background: white;\n"
"border-radius: 5px;\n"
"border: 1px solid #D3D3D3")
        self.frmlight_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmlight_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmlight_2.setObjectName("frmlight_2")
        self.txtRecx1 = QtWidgets.QLineEdit(self.frmlight_2)
        self.txtRecx1.setGeometry(QtCore.QRect(190, 110, 41, 31))
        self.txtRecx1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txtRecx1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtRecx1.setReadOnly(True)
        self.txtRecx1.setObjectName("txtRecx1")
        self.btnapplyroi = QtWidgets.QPushButton(self.frmlight_2)
        self.btnapplyroi.setGeometry(QtCore.QRect(270, 220, 111, 36))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnapplyroi.setFont(font)
        self.btnapplyroi.setStyleSheet("QPushButton#btnapplyroi:hover {background-color: black;\n"
"color: white;}\n"
"QPushButton#btnapplyroi {\n"
"border-radius: 10px;\n"
"background: rgb(41, 39, 40);\n"
"color: white;\n"
"}")
        self.btnapplyroi.setObjectName("btnapplyroi")
        self.btncancelroi = QtWidgets.QPushButton(self.frmlight_2)
        self.btncancelroi.setGeometry(QtCore.QRect(140, 220, 111, 36))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btncancelroi.setFont(font)
        self.btncancelroi.setStyleSheet("QPushButton#btncancelroi:hover {background-color: black;\n"
"color: white;}\n"
"QPushButton#btncancelroi {\n"
"border-radius: 10px;\n"
"background: rgb(41, 39, 40);\n"
"color: white;\n"
"}")
        self.btncancelroi.setObjectName("btncancelroi")
        self.lblroi = QtWidgets.QLabel(self.frmlight_2)
        self.lblroi.setGeometry(QtCore.QRect(20, 10, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblroi.setFont(font)
        self.lblroi.setStyleSheet("border: none;")
        self.lblroi.setObjectName("lblroi")
        self.lblrect = QtWidgets.QLabel(self.frmlight_2)
        self.lblrect.setGeometry(QtCore.QRect(40, 110, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblrect.setFont(font)
        self.lblrect.setStyleSheet("border: none;")
        self.lblrect.setObjectName("lblrect")
        self.txtRecy1 = QtWidgets.QLineEdit(self.frmlight_2)
        self.txtRecy1.setGeometry(QtCore.QRect(240, 110, 41, 31))
        self.txtRecy1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtRecy1.setReadOnly(True)
        self.txtRecy1.setObjectName("txtRecy1")
        self.lblx1 = QtWidgets.QLabel(self.frmlight_2)
        self.lblx1.setGeometry(QtCore.QRect(200, 80, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblx1.setFont(font)
        self.lblx1.setStyleSheet("border: none;")
        self.lblx1.setObjectName("lblx1")
        self.lblrect_3 = QtWidgets.QLabel(self.frmlight_2)
        self.lblrect_3.setGeometry(QtCore.QRect(250, 80, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblrect_3.setFont(font)
        self.lblrect_3.setStyleSheet("border: none;")
        self.lblrect_3.setObjectName("lblrect_3")
        self.lblx2 = QtWidgets.QLabel(self.frmlight_2)
        self.lblx2.setGeometry(QtCore.QRect(300, 80, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblx2.setFont(font)
        self.lblx2.setStyleSheet("border: none;")
        self.lblx2.setObjectName("lblx2")
        self.lbly2 = QtWidgets.QLabel(self.frmlight_2)
        self.lbly2.setGeometry(QtCore.QRect(350, 80, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbly2.setFont(font)
        self.lbly2.setStyleSheet("border: none;")
        self.lbly2.setObjectName("lbly2")
        self.txtRecx2 = QtWidgets.QLineEdit(self.frmlight_2)
        self.txtRecx2.setGeometry(QtCore.QRect(290, 110, 41, 31))
        self.txtRecx2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtRecx2.setReadOnly(True)
        self.txtRecx2.setObjectName("txtRecx2")
        self.txtRecy2 = QtWidgets.QLineEdit(self.frmlight_2)
        self.txtRecy2.setGeometry(QtCore.QRect(340, 110, 41, 31))
        self.txtRecy2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtRecy2.setReadOnly(True)
        self.txtRecy2.setObjectName("txtRecy2")
        self.lblline = QtWidgets.QLabel(self.frmlight_2)
        self.lblline.setGeometry(QtCore.QRect(40, 170, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblline.setFont(font)
        self.lblline.setStyleSheet("border: none;")
        self.lblline.setObjectName("lblline")
        self.txtLinex2 = QtWidgets.QLineEdit(self.frmlight_2)
        self.txtLinex2.setGeometry(QtCore.QRect(290, 170, 41, 31))
        self.txtLinex2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtLinex2.setReadOnly(True)
        self.txtLinex2.setObjectName("txtLinex2")
        self.txtLinex1 = QtWidgets.QLineEdit(self.frmlight_2)
        self.txtLinex1.setGeometry(QtCore.QRect(190, 170, 41, 31))
        self.txtLinex1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtLinex1.setReadOnly(True)
        self.txtLinex1.setObjectName("txtLinex1")
        self.txtLiney2 = QtWidgets.QLineEdit(self.frmlight_2)
        self.txtLiney2.setGeometry(QtCore.QRect(340, 170, 41, 31))
        self.txtLiney2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtLiney2.setReadOnly(True)
        self.txtLiney2.setObjectName("txtLiney2")
        self.txtLiney1 = QtWidgets.QLineEdit(self.frmlight_2)
        self.txtLiney1.setGeometry(QtCore.QRect(240, 170, 41, 31))
        self.txtLiney1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtLiney1.setReadOnly(True)
        self.txtLiney1.setObjectName("txtLiney1")
        self.btndrawroi = QtWidgets.QPushButton(self.frmlight_2)
        self.btndrawroi.setGeometry(QtCore.QRect(400, 110, 111, 36))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btndrawroi.setFont(font)
        self.btndrawroi.setStyleSheet("QPushButton#btndrawroi:hover {background-color: black;\n"
"color: white;}\n"
"QPushButton#btndrawroi {\n"
"border-radius: 10px;\n"
"background: rgb(41, 39, 40);\n"
"color: white;\n"
"}")
        self.btndrawroi.setObjectName("btndrawroi")
        self.btnpreviewroi = QtWidgets.QPushButton(self.frmlight_2)
        self.btnpreviewroi.setGeometry(QtCore.QRect(400, 170, 111, 36))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnpreviewroi.setFont(font)
        self.btnpreviewroi.setStyleSheet("QPushButton#btnpreviewroi:hover {background-color: black;\n"
"color: white;}\n"
"QPushButton#btnpreviewroi {\n"
"border-radius: 10px;\n"
"background: rgb(41, 39, 40);\n"
"color: white;\n"
"}")
        self.btnpreviewroi.setObjectName("btnpreviewroi")
        self.btnback1 = QtWidgets.QPushButton(self.tabroi)
        self.btnback1.setGeometry(QtCore.QRect(80, 190, 61, 61))
        self.btnback1.setStyleSheet("border: none;\n"
"background: white;\n"
"border-radius: 30px;\n"
"border: 1px solid #D3D3D3")
        self.btnback1.setText("")
        self.btnback1.setIcon(icon15)
        self.btnback1.setIconSize(QtCore.QSize(35, 35))
        self.btnback1.setObjectName("btnback1")
        self.tabright.addTab(self.tabroi, "")
        self.btnhome = QtWidgets.QPushButton(self.centralwidget)
        self.btnhome.setGeometry(QtCore.QRect(0, 210, 210, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnhome.setFont(font)
        self.btnhome.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnhome.setStyleSheet("QPushButton#btnhome:hover {background-color: rgb(17, 17, 17);}\n"
"QPushButton#btnhome {\n"
"color: white; border: none; text-align: left;\n"
"padding-left: 45px;\n"
"}")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/traffic/Icon/screen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnhome.setIcon(icon16)
        self.btnhome.setIconSize(QtCore.QSize(25, 25))
        self.btnhome.setFlat(True)
        self.btnhome.setObjectName("btnhome")
        self.btnsetup = QtWidgets.QPushButton(self.centralwidget)
        self.btnsetup.setGeometry(QtCore.QRect(0, 270, 210, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnsetup.setFont(font)
        self.btnsetup.setStyleSheet("QPushButton#btnsetup:hover {background-color: rgb(17, 17, 17);}\n"
"QPushButton#btnsetup {\n"
"color: white; border: none; text-align: left;\n"
"padding-left: 45px;\n"
"}")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/traffic/Icon/setup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnsetup.setIcon(icon17)
        self.btnsetup.setIconSize(QtCore.QSize(25, 25))
        self.btnsetup.setObjectName("btnsetup")
        self.btnmonitor = QtWidgets.QPushButton(self.centralwidget)
        self.btnmonitor.setGeometry(QtCore.QRect(0, 330, 210, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnmonitor.setFont(font)
        self.btnmonitor.setStyleSheet("QPushButton#btnmonitor:hover {background-color: rgb(17, 17, 17);}\n"
"QPushButton#btnmonitor {\n"
"color: white; border: none; text-align: left;\n"
"padding-left: 45px;\n"
"}")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/traffic/Icon/cctv.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnmonitor.setIcon(icon18)
        self.btnmonitor.setIconSize(QtCore.QSize(25, 25))
        self.btnmonitor.setObjectName("btnmonitor")
        self.lblupper = QtWidgets.QLabel(self.centralwidget)
        self.lblupper.setGeometry(QtCore.QRect(210, 0, 851, 21))
        self.lblupper.setStyleSheet("background-color: #FFCF06;")
        self.lblupper.setText("")
        self.lblupper.setObjectName("lblupper")
        self.lblhome = QtWidgets.QLabel(self.centralwidget)
        self.lblhome.setGeometry(QtCore.QRect(0, 210, 10, 51))
        self.lblhome.setStyleSheet("background-color: #FFCF06;")
        self.lblhome.setText("")
        self.lblhome.setObjectName("lblhome")
        self.lblsetup = QtWidgets.QLabel(self.centralwidget)
        self.lblsetup.setGeometry(QtCore.QRect(0, 270, 10, 51))
        self.lblsetup.setStyleSheet("background-color: #FFCF06;")
        self.lblsetup.setText("")
        self.lblsetup.setObjectName("lblsetup")
        self.lblmonitor = QtWidgets.QLabel(self.centralwidget)
        self.lblmonitor.setGeometry(QtCore.QRect(0, 330, 10, 51))
        self.lblmonitor.setStyleSheet("background-color: #FFCF06;")
        self.lblmonitor.setText("")
        self.lblmonitor.setObjectName("lblmonitor")
        self.btnreport = QtWidgets.QPushButton(self.centralwidget)
        self.btnreport.setGeometry(QtCore.QRect(0, 390, 210, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnreport.setFont(font)
        self.btnreport.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnreport.setStyleSheet("QPushButton#btnreport:hover {background-color: rgb(17, 17, 17);}\n"
"QPushButton#btnreport {\n"
"color: white; border: none; text-align: left;\n"
"padding-left: 45px;\n"
"}")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/traffic/Icon/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnreport.setIcon(icon19)
        self.btnreport.setIconSize(QtCore.QSize(25, 25))
        self.btnreport.setFlat(True)
        self.btnreport.setObjectName("btnreport")
        self.lblreport = QtWidgets.QLabel(self.centralwidget)
        self.lblreport.setGeometry(QtCore.QRect(0, 390, 10, 51))
        self.lblreport.setStyleSheet("background-color: #FFCF06;")
        self.lblreport.setText("")
        self.lblreport.setObjectName("lblreport")
        self.btnabout = QtWidgets.QPushButton(self.centralwidget)
        self.btnabout.setGeometry(QtCore.QRect(0, 450, 210, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnabout.setFont(font)
        self.btnabout.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnabout.setStyleSheet("QPushButton#btnabout:hover {background-color: rgb(17, 17, 17);}\n"
"QPushButton#btnabout {\n"
"color: white; border: none; text-align: left;\n"
"padding-left: 45px;\n"
"}")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/traffic/Icon/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnabout.setIcon(icon20)
        self.btnabout.setIconSize(QtCore.QSize(25, 25))
        self.btnabout.setFlat(True)
        self.btnabout.setObjectName("btnabout")
        self.lblabout = QtWidgets.QLabel(self.centralwidget)
        self.lblabout.setGeometry(QtCore.QRect(0, 450, 10, 51))
        self.lblabout.setStyleSheet("background-color: #FFCF06;")
        self.lblabout.setText("")
        self.lblabout.setObjectName("lblabout")
        self.btnlogo1 = QtWidgets.QPushButton(self.centralwidget)
        self.btnlogo1.setGeometry(QtCore.QRect(40, 40, 121, 121))
        self.btnlogo1.setStyleSheet("QPushButton#btnlogo1 {\n"
"border: none;\n"
"border-radius: 60px;\n"
"background:  #FFCF06;\n"
"}")
        self.btnlogo1.setText("")
        self.btnlogo1.setIcon(icon2)
        self.btnlogo1.setIconSize(QtCore.QSize(60, 60))
        self.btnlogo1.setObjectName("btnlogo1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1060, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(False)
        self.statusbar.setStyleSheet("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabright.setCurrentIndex(4)
        self.listWidget.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Traffic Light Violation Monitoring"))
        self.btnbrowse1.setText(_translate("MainWindow", "Browse..."))
        self.label_4.setText(_translate("MainWindow", "Captured Image"))
        self.btnreporthome.setText(_translate("MainWindow", "Report"))
        self.label_6.setText(_translate("MainWindow", "See Report Here"))
        self.label_7.setText(_translate("MainWindow", "Today"))
        self.lbldatehome.setText(_translate("MainWindow", "Thursday, 27 June 2019"))
        self.label_9.setText(_translate("MainWindow", "Aplikasi Pengawasan Pelanggaran Lalu Lintas"))
        self.tabright.setTabText(self.tabright.indexOf(self.tabhome), _translate("MainWindow", "Home"))
        self.label.setText(_translate("MainWindow", "Traffic Light"))
        self.label_2.setText(_translate("MainWindow", "Detection Area"))
        self.tabright.setTabText(self.tabright.indexOf(self.tabsetup), _translate("MainWindow", "Setup"))
        self.btnstart.setText(_translate("MainWindow", "Start"))
        self.btnstop.setText(_translate("MainWindow", "Stop"))
        self.tabright.setTabText(self.tabright.indexOf(self.tabmonitor), _translate("MainWindow", "Monitoring"))
        self.btnprint.setText(_translate("MainWindow", "Print"))
        self.dateEdit_2.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.btnopen.setText(_translate("MainWindow", "Browse..."))
        self.btnsearch.setToolTip(_translate("MainWindow", "Search"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.label_3.setText(_translate("MainWindow", "s/d"))
        self.tabright.setTabText(self.tabright.indexOf(self.tabreport), _translate("MainWindow", "Report"))
        self.label_5.setText(_translate("MainWindow", "Aplikasi Pengawasan"))
        self.lblimage_2.setText(_translate("MainWindow", "Versi 1.0"))
        self.label_8.setText(_translate("MainWindow", "Pelanggaran Lalu Lintas"))
        self.lblimage_3.setText(_translate("MainWindow", "Copyright @ 2019, Adi Andoyo"))
        self.lblimage_4.setText(_translate("MainWindow", "Ditulis dengan :"))
        self.lblimage_5.setText(_translate("MainWindow", "Python 3.6.5"))
        self.lblimage_6.setText(_translate("MainWindow", "PyQT 5.12.2 "))
        self.lblimage_7.setText(_translate("MainWindow", "OpenCV 4.0.0"))
        self.lblimage_8.setText(_translate("MainWindow", "STMIK Widya Dharma Pontianak"))
        self.tabright.setTabText(self.tabright.indexOf(self.tababout), _translate("MainWindow", "About"))
        self.btnapplylight.setText(_translate("MainWindow", "Apply"))
        self.btncancellight.setText(_translate("MainWindow", "Cancel"))
        self.lbltraffic.setText(_translate("MainWindow", "Traffic Light"))
        self.lbltraffic_2.setText(_translate("MainWindow", "Red Light"))
        self.lbltraffic_3.setText(_translate("MainWindow", "Yellow Light"))
        self.lbltraffic_4.setText(_translate("MainWindow", "Green Light"))
        self.lbltraffic_5.setText(_translate("MainWindow", "sec"))
        self.lbltraffic_6.setText(_translate("MainWindow", "sec"))
        self.lbltraffic_7.setText(_translate("MainWindow", "sec"))
        self.tabright.setTabText(self.tabright.indexOf(self.tablight), _translate("MainWindow", "Light"))
        self.btnapplyroi.setText(_translate("MainWindow", "Apply"))
        self.btncancelroi.setText(_translate("MainWindow", "Cancel"))
        self.lblroi.setText(_translate("MainWindow", "Detection Area"))
        self.lblrect.setText(_translate("MainWindow", "Rectangle Area"))
        self.lblx1.setText(_translate("MainWindow", "X1"))
        self.lblrect_3.setText(_translate("MainWindow", "Y1"))
        self.lblx2.setText(_translate("MainWindow", "X2"))
        self.lbly2.setText(_translate("MainWindow", "Y2"))
        self.lblline.setText(_translate("MainWindow", "Detection Line"))
        self.btndrawroi.setText(_translate("MainWindow", "Draw Area"))
        self.btnpreviewroi.setText(_translate("MainWindow", "Preview"))
        self.tabright.setTabText(self.tabright.indexOf(self.tabroi), _translate("MainWindow", "ROI"))
        self.btnhome.setText(_translate("MainWindow", "   Home"))
        self.btnsetup.setText(_translate("MainWindow", "   Setup"))
        self.btnmonitor.setText(_translate("MainWindow", "   Monitoring"))
        self.btnreport.setText(_translate("MainWindow", "   Report"))
        self.btnabout.setText(_translate("MainWindow", "   About"))


import zui


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
